### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ewxn** [Vezqi/Discrim-Bot#1]
```main.js:35
});
 ^

SyntaxError: Unexpected token )
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3```

**Comment by tenasa** [comment]
replace the last few lines so
```
  if (myDiscriminator.includes(bot.user.discriminator)) {
    console.log(`I successfully got the discrim ${bot.user.discriminator}!`)
    process.exit();
  }
});
```

**Comment by ewxn** [comment]
Thank you that did it, you might want to update the source on the repo :)
